#!/bin/bash

run_help() {

cat <<EOT
OS X dotfiles - Nicolas Gallagher, Jose Pablo Peralta -

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    -l, --list      Print a list of additional software to install
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/Sejopc/dotfiles-2

Copyright (c) Nicolas Gallagher, Jose Pablo Peralta
Licensed under the MIT license.
EOT

}
